# Generated by Django 5.1.4 on 2024-12-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_remove_measurement_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
