# Generated by Django 5.1.4 on 2024-12-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_measurement_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor',
            new_name='sensor_id',
        ),
    ]
