# Generated by Django 5.1.4 on 2024-12-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0005_rename_sensor_measurement_sensor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='image',
            field=models.ImageField(max_length=50, null=True, upload_to=''),
        ),
    ]
